# Generated by Django 5.2.3 on 2025-07-04 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_is_group_chat_chatsession_room_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='room_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
